import "./globals.css";
import Header from "../../components/header/Header";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
// import { notFound } from 'next/navigation';
// import { routing } from '@/i18n/routing';

export const metadata: Metadata = {
  title: "WOLF APP",
  description: "Generated by Youssef Elmahallawy",
};

export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {

  // if (!routing.locales.includes(locale as any)) {
  //   notFound();
  // }

  // const { locale } = await params;
  const messages = await getMessages();
  
  return (
    <html lang={locale}>
      <body dir="rtl">
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}